services:
  server:
    image: maven:3-amazoncorretto-21
    command: mvn clean spring-boot:run
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - ../:/usr/src/todo:rw
    working_dir: /usr/src/todo
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/todo-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=todo-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432
    volumes:
      - ../db:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d todo-db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    